[build]
  publish = "dist"
  command = "node build-client.js"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://cuca-beer.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"