[build]
  publish = "dist/public"
  command = "vite build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  # Add your Vercel URL here
  VITE_API_URL = "https://your-project.vercel.app"